const data = [
{title: '爱听4G', all : false,
img:'images/aiting.png',
children:[
  {title: '运营商',checked: false},
  {title: '互联网',checked: false},
  {title: '电影电视配乐',checked: false},
  {title: '游戏',checked: false},
  {title: '卡拉OK',checked: false},
  {title: '音像制品',checked: false},
  {title: '其他',checked: false}]},
{title: '百度音乐', all : false,
img:'images/baidu.png',
children:[
  {title: '运营商',checked: false},
  {title: '互联网',checked: false},
  {title: '电影电视配乐',checked: false},
  {title: '游戏',checked: false},
  {title: '卡拉OK',checked: false},
  {title: '音像制品',checked: false},
  {title: '其他',checked: false}]},
{title: '多米音乐', all : false,
img:'images/duomi.png',
children:[
  {title: '运营商',checked: false},
  {title: '互联网',checked: false},
  {title: '电影电视配乐',checked: false},
  {title: '游戏',checked: false},
  {title: '卡拉OK',checked: false},
  {title: '音像制品',checked: false},
  {title: '其他',checked: false}]},
{title: '酷我音乐', all : false,
img:'images/kuwo.png',
children:[
  {title: '运营商',checked: false},
  {title: '互联网',checked: false},
  {title: '电影电视配乐',checked: false},
  {title: '游戏',checked: false},
  {title: '卡拉OK',checked: false},
  {title: '音像制品',checked: false},
  {title: '其他',checked: false}]},
{title: '咪咕音乐',  all : false,
img:'images/migu.png',
children:[
  {title: '运营商',checked: false},
  {title: '互联网',checked: false},
  {title: '电影电视配乐',checked: false},
  {title: '游戏',checked: false},
  {title: '卡拉OK',checked: false},
  {title: '音像制品',checked: false},
  {title: '其他',checked: false}]},
{title: '天天动听', all : false,
img:'images/tiantiandongting.png',
children:[
  {title: '运营商',checked: false},
  {title: '互联网',checked: false},
  {title: '电影电视配乐',checked: false},
  {title: '游戏',checked: false},
  {title: '卡拉OK',checked: false},
  {title: '音像制品',checked: false},
  {title: '其他',checked: false}]},
{title: '网易云音乐',  all : false,
img:'images/wangyiyun.png',
children:[
  {title: '运营商',checked: false},
  {title: '互联网',checked: false},
  {title: '电影电视配乐',checked: false},
  {title: '游戏',checked: false},
  {title: '卡拉OK',checked: false},
  {title: '音像制品',checked: false},
  {title: '其他',checked: false}]},
{title: '虾米音乐', all : false,
img:'images/xiami.png',
children:[
  {title: '运营商',checked: false},
  {title: '互联网',checked: false},
  {title: '电影电视配乐',checked: false},
  {title: '游戏',checked: false},
  {title: '卡拉OK',checked: false},
  {title: '音像制品',checked: false},
  {title: '其他',checked: false}]},
{title: '音乐V榜', all : false,
img:'images/vbang.png',
children:[
  {title: '运营商',checked: false},
  {title: '互联网',checked: false},
  {title: '电影电视配乐',checked: false},
  {title: '游戏',checked: false},
  {title: '卡拉OK',checked: false},
  {title: '音像制品',checked: false},
  {title: '其他',checked: false}]},
{title: '余音', all : false,
img:'images/yuyin.png',
children:[
  {title: '运营商',checked: false},
  {title: '互联网',checked: false},
  {title: '电影电视配乐',checked: false},
  {title: '游戏',checked: false},
  {title: '卡拉OK',checked: false},
  {title: '音像制品',checked: false},
  {title: '其他',checked: false}]},
{title: 'QQ音乐', all : false,
img:'images/qq.png',
children:[
  {title: '运营商',checked: false},
  {title: '互联网',checked: false},
  {title: '电影电视配乐',checked: false},
  {title: '游戏',checked: false},
  {title: '卡拉OK',checked: false},
  {title: '音像制品',checked: false},
  {title: '其他',checked: false}]},
{title: '酷狗音乐', all : false,
img:'images/aiting.png',
children:[
  {title: '运营商',checked: false},
  {title: '互联网',checked: false},
  {title: '电影电视配乐',checked: false},
  {title: '游戏',checked: false},
  {title: '卡拉OK',checked: false},
  {title: '音像制品',checked: false},
  {title: '其他',checked: false}]},
{title: '搜狐音乐', all : false,
img:'images/aiting.png',
children:[
  {title: '运营商',checked: false},
  {title: '互联网',checked: false},
  {title: '电影电视配乐',checked: false},
  {title: '游戏',checked: false},
  {title: '卡拉OK',checked: false},
  {title: '音像制品',checked: false},
  {title: '其他',checked: false}]},
{title: '阿里音乐', all : false,
img:'images/aiting.png',
children:[
  {title: '运营商',checked: false},
  {title: '互联网',checked: false},
  {title: '电影电视配乐',checked: false},
  {title: '游戏',checked: false},
  {title: '卡拉OK',checked: false},
  {title: '音像制品',checked: false},
  {title: '其他',checked: false}]},
{title: '秀米音乐',  all : false,
img:'images/aiting.png',
children:[
  {title: '运营商',checked: false},
  {title: '互联网',checked: false},
  {title: '电影电视配乐',checked: false},
  {title: '游戏',checked: false},
  {title: '卡拉OK',checked: false},
  {title: '音像制品',checked: false},
  {title: '其他',checked: false}]},
  {title: '畅想音乐', all : false,
  img:'images/changxiang.png',
  children:[
    {title: '运营商',checked: false},
    {title: '互联网',checked: false},
    {title: '电影电视配乐',checked: false},
    {title: '游戏',checked: false},
    {title: '卡拉OK',checked: false},
    {title: '音像制品',checked: false},
    {title: '其他',checked: false}]},
  {title: 'jokey', all : false,
  img:'images/jokey.png',
  children:[
    {title: '运营商',checked: false},
    {title: '互联网',checked: false},
    {title: '电影电视配乐',checked: false},
    {title: '游戏',checked: false},
    {title: '卡拉OK',checked: false},
    {title: '音像制品',checked: false},
    {title: '其他',checked: false}]},
  {title: 'melocloud', all : false,
  img:'images/melocloud.png',
  children:[
    {title: '运营商',checked: false},
    {title: '互联网',checked: false},
    {title: '电影电视配乐',checked: false},
    {title: '游戏',checked: false},
    {title: '卡拉OK',checked: false},
    {title: '音像制品',checked: false},
    {title: '其他',checked: false}]},
  {title: 'muplay', all : false,
  img:'images/muplay.png',
  children:[
    {title: '运营商',checked: false},
    {title: '互联网',checked: false},
    {title: '电影电视配乐',checked: false},
    {title: '游戏',checked: false},
    {title: '卡拉OK',checked: false},
    {title: '音像制品',checked: false},
    {title: '其他',checked: false}]},
  {title: 'UU音乐',  all : false,
  img:'images/uu.png',
  children:[
    {title: '运营商',checked: false},
    {title: '互联网',checked: false},
    {title: '电影电视配乐',checked: false},
    {title: '游戏',checked: false},
    {title: '卡拉OK',checked: false},
    {title: '音像制品',checked: false},
    {title: '其他',checked: false}]}]
export default data;
